[project]
name = "readonlydict"
version = "1.0.0rc1"
description = "Drop-in read-only dictionary with 100% typing and runtime compatibility"
readme = "README.md"
keywords = [
    "dictionary",
    "hashable",
    "immutable",
    "mapping",
    "python",
    "read-only",
    "typing",
]
requires-python = ">=3.10,<4.0"
dependencies = ["typing-extensions>=4,<5"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[[project.authors]]
name = "Akio Taniguchi"
email = "a-taniguchi@mail.kitami-it.ac.jp"

[project.license]
file = "LICENSE"

[project.urls]
homepage = "https://astropenguin.github.io/readonlydict"
repository = "https://github.com/astropenguin/readonlydict"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25,<27",
    "ipython>=8,<10",
    "mypy>=1,<2",
    "myst-parser>=3,<5",
    "pydata-sphinx-theme>=0.16,<1.0",
    "pyright>=1,<2",
    "pytest>=9,<10",
    "sphinx>=8,<9",
]

[tool.mypy]
strict = true

[tool.pyright]
typeCheckingMode = "strict"
